### ISSUE TITLE
"Sign-up to endorse" link doesn't trigger email client

### ISSUE THREAD

**Issue by jessjoschwartz** [covid-projections/covid-projections#361] opened 2020-04-02 07:41 UTC
*summary:*
"Sign-up to endorse" link doesn't trigger email client, it just produces a "mailto" prompt in the bottom left corner (which isn't very visible). 

*expected result:*
Clicking on "Sign-up to endorse" triggers email client.

*actual result:*

*environment (device, browser, mobile / web):*

*link:*

*screenshot (you can copy/paste images directly in):*
<img width="1274" alt="Screen Shot 2020-04-02 at 12 38 41 AM" src="https://user-images.githubusercontent.com/7066001/78222745-943bca80-747a-11ea-9e42-64b098eb8fa2.png">

**Comment by zjrosen1** [comment] 2020-04-02 09:05
@jessjoschwartz this is opening a mail client for me, can't reproduce

**Comment by jamestamplin** [comment] 2020-04-05 01:07
Also opening for me, I think this is your corp laptop, Jess.

Closing.

**Closed by jamestamplin** 2020-04-05 01:07 UTC
