### ISSUE TITLE
Cleanup ModelPage

### ISSUE THREAD

**Issue by zjrosen1** [covid-projections/covid-projections#126] opened 2020-03-22 19:37 UTC
The ModelPage was the first page thrown together and could use some love, pulling out components adding cleaning up the code

**Comment by rachelrf** [comment] 2020-03-22 22:36
I can take a look at this in conjunction with this issue: https://github.com/covid-projections/covid-projections/issues/118

**Comment by rachelrf** [comment] 2020-03-22 22:36
Duplicate of #118

**Closed by rachelrf** 2020-03-22 22:36 UTC
Labels: technical debt
