### ISSUE TITLE
County is 'colored in', but graphs populate no data

### ISSUE THREAD

**Issue by jamestamplin** [covid-projections/covid-projections#413] opened 2020-04-04 22:01 UTC
On click, there's no data in the graphs, just the hospitalization line.

In these counties:

Coffee | Alabama
Waupaca | Wisconsin
Gallia | Ohio
Garfield | Washington
Hampton | South Carolina
Conway | Arkansas
Henry | Missouri
Mercer | North Dakota
Pasquotank, Chowan, Swain | North Carolina
Gage County | Nebraska

**Comment by mikelehen** [comment] 2020-04-05 05:37
Example broken page: https://covidactnow.org/us/al/county/coffee_county
FIPS 01031
It looks like the modeled data is just all 0's: https://covidactnow.org/data/county/AL.01031.0.json

@ghop02 Maybe you could take a look?  Perhaps we need to have the backend omit counties for which we have no cases or something?

**Comment by ghop02** [comment] 2020-04-05 06:34
So it looks like all of those have cases - on my local branch with (almost) updated data most of them did. 

I think (though haven't fully confirmed) this was happening because of the 4 day interval. I think there were cases for less than 4 days and then it was starting the model from a day before there was any data.  It would make sense, but haven't 100% confirmed the logic, just my theory for now

**Comment by jamestamplin** [comment] 2020-04-06 02:14
Beaver County, Utah has the same behaviour, FYI

**Comment by mikelehen** [comment] 2020-04-06 23:55
Fix for this is now deployed.  Confirmed Beaver, UT and Elko County, NV both work now.

**Closed by mikelehen** 2020-04-06 23:55 UTC

**Comment by jamestamplin** [comment] 2020-04-06 23:56
[image: 🚀]

James Tamplin
tinyletter.com/jamest (2-3 emails / yr on what I'm up to)
