### ISSUE TITLE
No “poor/strict compliance” on Model Reference and Assumptions doc

### ISSUE THREAD

**Issue by hannahleeCAN** [covid-projections/covid-projections#377] opened 2020-04-02 13:31 UTC
*summary:*
Definition for “poor/strict compliance” is not on the Model Reference and Assumptions document as claimed.

What definition does Covid Act Now use for “social distancing” and “stay at home”? How about “poor/strict compliance” (re. “stay at home”)?

All these definitions — and much more — can be found in our Model Reference and Assumptions document.

*expected result:*
Definition of “poor/strict compliance”

*actual result:*
None

*environment (device, browser, mobile / web):*
Web

*link:*
https://covidactnow.org/faq

*screenshot (you can copy/paste images directly in):*
<img width="882" alt="Screen Shot 2020-04-02 at 6 27 47 AM" src="https://user-images.githubusercontent.com/63055368/78255012-95392000-74ab-11ea-8868-fc35e3d98e11.png">
<img width="1091" alt="Screen Shot 2020-04-02 at 6 28 14 AM" src="https://user-images.githubusercontent.com/63055368/78255026-979b7a00-74ab-11ea-823d-96561d2a3d54.png">

**Comment by igorkofman** [comment] 2020-04-09 00:09
dupe of https://github.com/covid-projections/covid-projections/issues/347

**Closed by igorkofman** 2020-04-09 00:09 UTC
